export const IMAGE_SEARCH_BOX_UPDATED = 'IMAGE_SEARCH_BOX_UPDATE'
export const UPDATE_IMAGE_LIST = 'UPDATE_IMAGE_LIST'
export const FILTERED_IMAGE_LIST = 'FILTERED_IMAGE_LIST'
export const TOGGLE_IMAGE_LOADER = 'TOGGLE_IMAGE_LOADER'